name: Build exe with Pyinstaller

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build exe
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: src/dist/windows/vpc-get-high-scores-image.exe

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "src/dist/windows/vpc-get-high-scores-image.exe,src/GetAllHighScores.bat,src/playsound.exe,src/UpdateHighScoreStart.mp3,src/UpdateHighScoreStop.mp3"
        token: ${{ secrets.GH_TOKEN }}
        commit: ${{ github.sha }}
        tag: v0.9.4